name: Update rev
on: push
jobs:
  updaterev:
    name: Update rev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Run Actions script
        uses: actions/github-script@v3
        with:
          script: |
            const yaml = require("js-yaml")
            //const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/conda_release.js`)
            //console.log(script({github, context}))
