name: Update Conda dependencies
on:
  schedule:
    # Once a day
    - cron: "43 21 * * *"
jobs:
  updaterev:
    name: Update Conda dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout github-actions repo
        uses: actions/checkout@v2
        with:
          repository: Quantco/github-actions
          ref: update-conda-dependencies
          token: ${{ secrets.FQ_GH_TOKEN }}
          path: .github/quantco-actions
      - name: Update Conda dependencies
        uses: ./.github/quantco-actions/update-conda-dependencies
      - name: Create Pull Request
        id: cpr
        # This is the v3.10.0 tag but for security purposes we pin to the exact commit.
        uses: peter-evans/create-pull-request@9825ae65b1cb54b543b938503728b432a0176d29
        with:
          commit-message: "Update ${{ steps.update_conda_dependencies.outputs.updates }}"
          title: "Update ${{ steps.update_conda_dependencies.outputs.updates }}"
          body: |
            This PR was created by the update-conda-dependencies workflow as it detected new versions of some of the dependencies were released to conda-forge.
          branch: update-conda-dependencies
          delete-branch: true
